# Generated by Django 3.2.15 on 2025-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='request_data',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='дата запроса'),
        ),
    ]
