# Generated by Django 3.2.15 on 2025-08-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_auto_20250807_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='request_data',
            new_name='request_date',
        ),
    ]
