# Generated by Django 3.2.15 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250722_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('PROCESSING', 'Готовится'), ('IN_TRANSIT', 'Доставляется'), ('DONE', 'Выполнен')], default='NEW', max_length=50, verbose_name='статус'),
        ),
    ]
