# Generated by Django 3.2.15 on 2025-07-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('PROCESSING', 'Готовится'), ('IN_TRANSIT', 'Доставляется'), ('DONE', 'Выполнен')], db_index=True, default='NEW', max_length=50, verbose_name='статус'),
        ),
    ]
