# Generated by Django 3.2.15 on 2025-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20250727_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('NOT_PAID', 'Неоплачено'), ('ONLINE', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='NOT_PAID', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
