# Generated by Django 3.2.15 on 2025-08-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20250805_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
